# Generated by Django 5.1.5 on 2025-02-01 18:10

import django.core.validators
import django.db.models.deletion
import hub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('repository_url', models.URLField(verbose_name='Repository URL')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=hub.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Only PDF files are allowed.')])),
                ('cash_flow_models', models.ManyToManyField(blank=True, to='hub.cashflowmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=100, validators=[hub.models.validate_version])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('error', 'Error'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('cash_flow_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.cashflowmodel')),
            ],
        ),
    ]
