# Generated by Django 5.1.5 on 2025-02-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_machine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='ec2_instance_ip',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='private_key_path',
            new_name='ssh_key_path',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='username',
            new_name='ssh_username',
        ),
    ]
